#!/usr/bin/python
import os
import sys
import time
import json
from calendar import timegm
from datetime import timedelta, datetime
from operator import itemgetter

from hosted import CONFIG, NODE, UPSTREAM

CONFIG.restart_on_update()

def current_time():
    now = datetime.utcnow()
    timestamp = timegm(now.timetuple()) + now.microsecond / 1000000.
    return now, timestamp
            
def send_clock(now, ts):
    NODE.send('/clock/set:%f' % ts)

def main():
    while 1:
        now, ts = current_time()
        if now.year < 2000:
            print >>sys.stderr, "too soon"
            time.sleep(1)
            continue
        
        for i in xrange(60):
            now, ts = current_time()
            print >>sys.stderr, "time is", now, ts
            send_clock(now, ts)
            time.sleep(30)
        
if __name__ == "__main__":
    main()
